# Generated by Django 5.0.3 on 2024-03-24 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Price')),
                ('contacts', models.TextField(verbose_name='Contacts')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='Author of the ad')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to='callboard.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Advert',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Reply text')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of response')),
                ('accept', models.BooleanField(default=False, verbose_name='Accept')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created data')),
                ('advert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='callboard.advert', verbose_name='Advert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Author of the ad')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ['-created'],
            },
        ),
    ]
