# Generated by Django 5.0.3 on 2024-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0003_alter_advert_category_alter_response_advert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('tanks', 'Tanks'), ('healers', 'Healers'), ('dd', 'DD'), ('merchants', 'Merchants'), ('guildmasters', 'Guildmasters'), ('questgivers', 'Questgivers'), ('blacksmiths', 'Blacksmiths'), ('tanners', 'Tanners'), ('alchemists', 'Alchemists'), ('spell_masters', 'Spell Masters')], max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='advert',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='File'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
