# Generated by Django 5.0.3 on 2024-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0005_alter_response_options_remove_response_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Contacts'),
        ),
    ]
