# Generated by Django 5.0.3 on 2024-04-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0006_alter_advert_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='price',
        ),
    ]
